describe("The RadioWithSettings function", function(){
  it("the call total should be R2.00, sms R1.00 and the total bill R3.00. The warning and critical values are reached true should be returned", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('2');
    radioWithSet.smsSet('1');
    radioWithSet.warningSet('1.50');
    radioWithSet.criticalSet('3');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '2.00');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '1.00');
    assert.deepEqual(radioWithSet.theTotal(), '3.00');
    assert.deepEqual(radioWithSet.yellow(), true);
    assert.deepEqual(radioWithSet.red(), true);
  });
  it("the call amount set to R2.00 entered 4 times, sms set to R0.00 entered 3 times. It should return total bill R6.50. The warning and critical values are reached, it should return true", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('2');
    radioWithSet.smsSet('');
    radioWithSet.warningSet('5');
    radioWithSet.criticalSet('6.50');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '6.50');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '0.00');
    assert.deepEqual(radioWithSet.theTotal(), '6.50');
    assert.deepEqual(radioWithSet.yellow(), true);
    assert.deepEqual(radioWithSet.red(), true);
  });
  it("the call amount set to R0.00 entered 3 times, sms set to R1.50 entered 5 times. It should return total bill R6.50. The warning and critical values are reached, it should return true", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('');
    radioWithSet.smsSet('1.50');
    radioWithSet.warningSet('5');
    radioWithSet.criticalSet('6.50');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '0.00');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '6.50');
    assert.deepEqual(radioWithSet.theTotal(), '6.50');
    assert.deepEqual(radioWithSet.yellow(), true);
    assert.deepEqual(radioWithSet.red(), true);
  });
  it("the call amount set to R0.00 entered 3 times, sms set to R1.50 entered 5 times. It should return total bill R7.50. It should return true for warning level reached and false for critical level reached", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('');
    radioWithSet.smsSet('1.50');
    radioWithSet.warningSet('5');
    radioWithSet.criticalSet('');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '0.00');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '7.50');
    assert.deepEqual(radioWithSet.theTotal(), '7.50');
    assert.deepEqual(radioWithSet.yellow(), true);
    assert.deepEqual(radioWithSet.red(), false);
  });
  it("the call amount set to R2.00 entered 3 times, sms set to R1.50 entered 5 times. It should return total bill R13.50. It should return true for warning level readed and false for critical level reached", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('2');
    radioWithSet.smsSet('1.50');
    radioWithSet.warningSet('10.20');
    radioWithSet.criticalSet('');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '6.00');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '7.50');
    assert.deepEqual(radioWithSet.theTotal(), '13.50');
    assert.deepEqual(radioWithSet.yellow(), true);
    assert.deepEqual(radioWithSet.red(), false);
  });
  it("the call amount set to R2.00 entered 3 times, sms set to R1.50 entered 5 times. It should return total bill R4.00. It should return false for warning level readed and true for critical level reached", function(){
    var radioWithSet = RadioWithSettings();
    radioWithSet.callSet('2');
    radioWithSet.smsSet('1.50');
    radioWithSet.warningSet('10.20');
    radioWithSet.criticalSet('4');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('call');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    radioWithSet.calculateEntry('sms');
    assert.deepEqual(radioWithSet.checkEntry('call'), '2.00');
    assert.deepEqual(radioWithSet.checkEntry('sms'), '2.00');
    assert.deepEqual(radioWithSet.theTotal(), '4.00');
    assert.deepEqual(radioWithSet.yellow(), false);
    assert.deepEqual(radioWithSet.red(), true);
  });
});
